version: '3.7'

services:
  mysql:
    container_name: category_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=category
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - category_network
networks:
  category_network: