spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: postgres
    password: postgres
    url: jdbc:h2:mem:adm_videos_test;DATABASE_TO_LOWER=true
  h2:
    console:
      enabled: true
      path: /h2